name: Unit Test

on:
  pull_request:
    branches:
      - main
    paths:
      - jade_job/**
      - tests/**
      - pyproject.toml
      - poetry.lock

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"

      - uses: Gr1N/setup-poetry@v4

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Dependencies and Run Tests
        run: |
          poetry install
          poetry run pytest -v
